name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: ${{ matrix.platform.name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - name: linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu

          - name: linux-riscv64
            os: ubuntu-latest
            target: riscv64gc-unknown-linux-gnu

          - name: windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc

          - name: windows-aarch64
            os: windows-latest
            target: aarch64-pc-windows-msvc

          - name: macos-x86_64
            os: macos-13
            target: x86_64-apple-darwin

          - name: macos-aarch64
            os: macos-14
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'macOS'
        run: |
          apt update
          apt install nasm

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install ffmpeg lame

      - name: Set up MSBuild (Windows)
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v2

      - name: Configure MSVC (Windows)
        if: |
          runner.os == 'Windows' &&
          (matrix.platform.target == 'x86_64-pc-windows-msvc' ||
           matrix.platform.target == 'aarch64-pc-windows-msvc')
        shell: powershell
        run: |
          $target = "${{ matrix.platform.target }}"
          $vcvars_arch = ""
          
          if ($target -eq "x86_64-pc-windows-msvc") {
            $vcvars_arch = "x64"
            Write-Host "Running vcvarsall.bat x64 for x86_64 target..."
          } elseif ($target -eq "aarch64-pc-windows-msvc") {
            $vcvars_arch = "x64_arm64"
            Write-Host "Running vcvarsall.bat x64_arm64 for aarch64 target..."
          } else {
            Write-Error "Unsupported Windows target for vcvarsall.bat: $target"
            exit 1
          }
          
          $scriptContent = @"
          @echo off
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" $vcvars_arch >nul
          set
          "@
          
          $tempScriptPath = Join-Path $env:TEMP "run_vcvars.bat"
          $scriptContent | Out-File $tempScriptPath -Encoding UTF8
          
          $vcvarsOutput = cmd.exe /c $tempScriptPath
          
          foreach ($line in $vcvarsOutput) {
            if ($line -match "^(.+?)=(.*)$") {
              $varName = $matches[1]
              $varValue = $matches[2]
              Add-Content -Path $Env:GITHUB_ENV -Value "$varName=$varValue"
            }
          }
          Remove-Item $tempScriptPath

      - name: Download FFmpeg (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          $target = "${{ matrix.platform.target }}"
          $ffmpeg_url = ""
          $ffmpeg_archive_name = ""

          if ($target -eq "x86_64-pc-windows-msvc") {
            $ffmpeg_url = 'https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2025-12-19-12-55/ffmpeg-n8.0.1-31-ge36046790a-win64-gpl-shared-8.0.zip'
            $ffmpeg_archive_name = 'ffmpeg-x64.zip'
            Write-Host "Downloading x64 FFmpeg..."
          } elseif ($target -eq "aarch64-pc-windows-msvc") {
            $ffmpeg_url = 'https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2025-12-19-12-55/ffmpeg-n8.0.1-31-ge36046790a-winarm64-gpl-shared-8.0.zip'
            $ffmpeg_archive_name = 'ffmpeg-arm64.zip'
            Write-Host "Downloading ARM64 FFmpeg..."
          } else {
            Write-Error "Unsupported Windows target: $target"
            exit 1
          }

          $archive = Join-Path $Env:USERPROFILE $ffmpeg_archive_name
          $dest    = Join-Path $Env:USERPROFILE 'ffmpeg'

          Invoke-WebRequest $ffmpeg_url -OutFile $archive -MaximumRedirection 5
          & (Join-Path $env:ProgramFiles '7-Zip\7z.exe') x $archive "-o$dest" -y
          Remove-Item $archive

          $dirs = Get-ChildItem $dest | Where-Object PSIsContainer
          if ($dirs.Count -eq 1) {
            Get-ChildItem $dirs[0].FullName | Move-Item -Destination $dest -Force
            Remove-Item $dirs[0].FullName -Recurse -Force
          }

          Add-Content -Path $Env:GITHUB_ENV -Value "FFMPEG_DIR=$dest"
          Add-Content -Path $Env:GITHUB_ENV -Value "INCLUDE=$dest\include;$Env:INCLUDE"
          Add-Content -Path $Env:GITHUB_ENV -Value "LIB=$dest\lib;$Env:LIB"
          Add-Content -Path $Env:GITHUB_ENV -Value "PATH=$dest\bin;$Env:PATH"

      - name: Build
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--release --features static --bin ilass"
#          strip: true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ilass-${{ matrix.platform.target }}
          path: target/${{ matrix.platform.target }}/release/ilass*

      - name: Release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: ilass
          target: ${{ matrix.platform.target }}
          changes-file: ""
